### ISSUE TITLE
order funcion

### ISSUE THREAD

**Issue by ddrr1337** [Endogen/TradeOgrePy#1]
i am a total noob, probably i am doing wrong but:
when i call order function it always return me this:
[]
Dont know if i am doing something wrong, just for testing i copied pasted the example line you have in README.md, but the response is always the same, no matter what pair input

**Comment by Endogen** [comment]
Hey, i guess this wasn't very clear in the README but you need to call the method like this:
```python
from tradeogre import TradeOgre

TradeOgre().order(uuid="1702a7bc-6a18-92c0-c1fe-aaf581d2352d", key="some_key", secret="some_secret"
```

I'VE JUST NOW REWORKED THE IMPLEMENTATION! Please make sure to grab the new version 😄 
And you have to replace `some_key` and `some_secret` with the correct key and secret from your TradeOgre account

or you can also do something like this:

```python
from tradeogre import TradeOgre

to = TradeOgre(key="01191d89c2ad11ac5eabca84f6ebe9c3", secret="cf695053bce02950c4ab08124335e593")

result_orders = to.orders(market="BTC-LOKI")
print(result_orders)

result_order = to.order(uuid="1702a7bc-6a18-92c0-c1fe-aaf581d2352d")
print(result_order)
```

And again you have to of course replace `1702a7bc-6a18-92c0-c1fe-aaf581d2352d` with the uuid of your own order

**Comment by ddrr1337** [comment]
Thanks, now is working perfect!!!!

**Comment by Endogen** [comment]
Great 😄
